if true then return {} end
-- return {
--   "folke/tokyonight.nvim",
--   name = "tokyonight",
--   priority = 1000,
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "tokyonight",
--     },
--   },
--   enabled = false,
-- }
